<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="nl_NL">
<context>
    <name>QKeySequenceEdit</name>
    <message>
        <source>Press shortcut</source>
        <translation>Gebruik sneltoets</translation>
    </message>
</context>
<context>
    <name>QPlatformTheme</name>
    <message>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>&amp;OK</source>
        <translation>&amp;OK</translation>
    </message>
    <message>
        <source>&amp;No</source>
        <translation>&amp;Nee</translation>
    </message>
    <message>
        <source>&amp;Yes</source>
        <translation>&amp;Ja</translation>
    </message>
    <message>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <source>Open</source>
        <translation>Openen</translation>
    </message>
    <message>
        <source>Save</source>
        <translation>Opslaan</translation>
    </message>
    <message>
        <source>&amp;Save</source>
        <translation>Op&amp;slaan</translation>
    </message>
    <message>
        <source>Abort</source>
        <translation>Afbreken</translation>
    </message>
    <message>
        <source>Apply</source>
        <translation>Toepassen</translation>
    </message>
    <message>
        <source>Close</source>
        <translation>Sluiten</translation>
    </message>
    <message>
        <source>Reset</source>
        <translation>Herstellen</translation>
    </message>
    <message>
        <source>Retry</source>
        <translation>Opnieuw</translation>
    </message>
    <message>
        <source>Restore Defaults</source>
        <translation>Standaardinstellingen</translation>
    </message>
    <message>
        <source>&amp;Close</source>
        <translation>Sl&amp;uiten</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Annulleren</translation>
    </message>
    <message>
        <source>Ignore</source>
        <translation>Negeren</translation>
    </message>
    <message>
        <source>Close without Saving</source>
        <translation>Sluiten zonder opslaan</translation>
    </message>
    <message>
        <source>N&amp;o to All</source>
        <translation>N&amp;ee op alles</translation>
    </message>
    <message>
        <source>Save All</source>
        <translation>Alles opslaan</translation>
    </message>
    <message>
        <source>&amp;Cancel</source>
        <translation>A&amp;nnulleren</translation>
    </message>
    <message>
        <source>Discard</source>
        <translation>Uitsluiten</translation>
    </message>
    <message>
        <source>Yes to &amp;All</source>
        <translation>Ja op a&amp;lles</translation>
    </message>
    <message>
        <source>Don&apos;t Save</source>
        <translation>Niet opslaan</translation>
    </message>
</context>
<context>
    <name>QShortcut</name>
    <message>
        <source>+</source>
        <translation></translation>
    </message>
    <message>
        <source>No</source>
        <translation></translation>
    </message>
    <message>
        <source>Up</source>
        <translation></translation>
    </message>
    <message>
        <source>Alt</source>
        <translation></translation>
    </message>
    <message>
        <source>F%1</source>
        <translation></translation>
    </message>
    <message>
        <source>Del</source>
        <translation></translation>
    </message>
    <message>
        <source>End</source>
        <translation></translation>
    </message>
    <message>
        <source>Esc</source>
        <translation></translation>
    </message>
    <message>
        <source>Ins</source>
        <translation></translation>
    </message>
    <message>
        <source>Tab</source>
        <translation></translation>
    </message>
    <message>
        <source>Yes</source>
        <translation></translation>
    </message>
    <message>
        <source>Back</source>
        <translation></translation>
    </message>
    <message>
        <source>Call</source>
        <translation></translation>
    </message>
    <message>
        <source>Ctrl</source>
        <translation></translation>
    </message>
    <message>
        <source>Down</source>
        <translation></translation>
    </message>
    <message>
        <source>Flip</source>
        <translation></translation>
    </message>
    <message>
        <source>Help</source>
        <translation></translation>
    </message>
    <message>
        <source>Home</source>
        <translation></translation>
    </message>
    <message>
        <source>Left</source>
        <translation></translation>
    </message>
    <message>
        <source>Menu</source>
        <translation></translation>
    </message>
    <message>
        <source>Meta</source>
        <translation></translation>
    </message>
    <message>
        <source>PgUp</source>
        <translation></translation>
    </message>
    <message>
        <source>Stop</source>
        <translation></translation>
    </message>
    <message>
        <source>Enter</source>
        <translation></translation>
    </message>
    <message>
        <source>Pause</source>
        <translation></translation>
    </message>
    <message>
        <source>Print</source>
        <translation></translation>
    </message>
    <message>
        <source>Right</source>
        <translation></translation>
    </message>
    <message>
        <source>Shift</source>
        <translation></translation>
    </message>
    <message>
        <source>Space</source>
        <translation></translation>
    </message>
    <message>
        <source>Media Record</source>
        <translation></translation>
    </message>
    <message>
        <source>Print Screen</source>
        <translation></translation>
    </message>
    <message>
        <source>Treble Down</source>
        <translation></translation>
    </message>
    <message>
        <source>Scroll Lock</source>
        <translation></translation>
    </message>
    <message>
        <source>Volume Down</source>
        <translation></translation>
    </message>
    <message>
        <source>Volume Mute</source>
        <translation></translation>
    </message>
    <message>
        <source>Media Previous</source>
        <translation></translation>
    </message>
    <message>
        <source>Home Page</source>
        <translation></translation>
    </message>
    <message>
        <source>Volume Up</source>
        <translation></translation>
    </message>
    <message>
        <source>Delete</source>
        <translation></translation>
    </message>
    <message>
        <source>Escape</source>
        <translation></translation>
    </message>
    <message>
        <source>Hangup</source>
        <translation></translation>
    </message>
    <message>
        <source>Insert</source>
        <translation></translation>
    </message>
    <message>
        <source>Bass Boost</source>
        <translation></translation>
    </message>
    <message>
        <source>PgDown</source>
        <translation></translation>
    </message>
    <message>
        <source>Return</source>
        <translation></translation>
    </message>
    <message>
        <source>Search</source>
        <translation></translation>
    </message>
    <message>
        <source>Select</source>
        <translation></translation>
    </message>
    <message>
        <source>SysReq</source>
        <translation></translation>
    </message>
    <message>
        <source>NumLock</source>
        <translation></translation>
    </message>
    <message>
        <source>ScrollLock</source>
        <translation></translation>
    </message>
    <message>
        <source>Context1</source>
        <translation></translation>
    </message>
    <message>
        <source>Context2</source>
        <translation></translation>
    </message>
    <message>
        <source>Context3</source>
        <translation></translation>
    </message>
    <message>
        <source>Context4</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Up</source>
        <translation></translation>
    </message>
    <message>
        <source>Open URL</source>
        <translation></translation>
    </message>
    <message>
        <source>Caps Lock</source>
        <translation></translation>
    </message>
    <message>
        <source>System Request</source>
        <translation></translation>
    </message>
    <message>
        <source>CapsLock</source>
        <translation></translation>
    </message>
    <message>
        <source>Backtab</source>
        <translation></translation>
    </message>
    <message>
        <source>Bass Up</source>
        <translation></translation>
    </message>
    <message>
        <source>Refresh</source>
        <translation></translation>
    </message>
    <message>
        <source>Launch Mail</source>
        <translation></translation>
    </message>
    <message>
        <source>Backspace</source>
        <translation></translation>
    </message>
    <message>
        <source>Bass Down</source>
        <translation></translation>
    </message>
    <message>
        <source>Standby</source>
        <translation></translation>
    </message>
    <message>
        <source>Treble Up</source>
        <translation></translation>
    </message>
    <message>
        <source>Num Lock</source>
        <translation></translation>
    </message>
    <message>
        <source>Number Lock</source>
        <translation></translation>
    </message>
    <message>
        <source>Favorites</source>
        <translation></translation>
    </message>
    <message>
        <source>Forward</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Down</source>
        <translation></translation>
    </message>
    <message>
        <source>Media Play</source>
        <translation></translation>
    </message>
    <message>
        <source>Media Stop</source>
        <translation></translation>
    </message>
    <message>
        <source>Media Next</source>
        <translation></translation>
    </message>
    <message>
        <source>Launch Media</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>QColorDialog</name>
    <message>
        <source>&amp;Pick Screen Color</source>
        <translation>&amp;Schermkleur kiezen</translation>
    </message>
    <message>
        <source>Cursor at %1, %2
Press ESC to cancel</source>
        <translation>Cursor op %1, %2
Druk ESC om te annulleren</translation>
    </message>
    <message>
        <source>&amp;Red:</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Sat:</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Val:</source>
        <translation></translation>
    </message>
    <message>
        <source>Hu&amp;e:</source>
        <translation></translation>
    </message>
    <message>
        <source>Select Color</source>
        <translation>Kleur kiezen</translation>
    </message>
    <message>
        <source>&amp;Add to Custom Colors</source>
        <translation>Toevoegen aan &amp;Aangepaste kleuren</translation>
    </message>
    <message>
        <source>Bl&amp;ue:</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Green:</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Basic colors</source>
        <translation>&amp;Basiskleuren</translation>
    </message>
    <message>
        <source>&amp;Custom colors</source>
        <translation>&amp;Aangepaste kleuren</translation>
    </message>
    <message>
        <source>A&amp;lpha channel:</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>QMessageBox</name>
    <message>
        <source>Yes</source>
        <translation>Ja</translation>
    </message>
    <message>
        <source>No</source>
        <translation>Nee</translation>
    </message>
    <message>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <source>Show Details...</source>
        <translation>Details tonen...</translation>
    </message>
    <message>
        <source>About Qt</source>
        <translation>Over Qt</translation>
    </message>
    <message>
        <source>Hide Details...</source>
        <translation>Details verbergen...</translation>
    </message>
</context>
<context>
    <name>QFontDialog</name>
    <message>
        <source>&amp;Font</source>
        <translation>&amp;Lettertype</translation>
    </message>
    <message>
        <source>&amp;Size</source>
        <translation>&amp;Grootte</translation>
    </message>
    <message>
        <source>Sample</source>
        <translation>Voorbeeld</translation>
    </message>
    <message>
        <source>Font st&amp;yle</source>
        <translation>&amp;Stijl</translation>
    </message>
    <message>
        <source>Wr&amp;iting System</source>
        <translation>Schrijf&amp;richting</translation>
    </message>
    <message>
        <source>Select Font</source>
        <translation>Lettertype kiezen</translation>
    </message>
    <message>
        <source>&amp;Underline</source>
        <translation>&amp;Onderstrepen</translation>
    </message>
    <message>
        <source>Effects</source>
        <translation>Effecten</translation>
    </message>
    <message>
        <source>Stri&amp;keout</source>
        <translation>Door&amp;halen</translation>
    </message>
</context>
<context>
    <name>QFontDatabase</name>
    <message>
        <source>Any</source>
        <translation></translation>
    </message>
    <message>
        <source>Lao</source>
        <translation></translation>
    </message>
    <message>
        <source>Bold</source>
        <translation></translation>
    </message>
    <message>
        <source>Demi</source>
        <translation></translation>
    </message>
    <message>
        <source>Thai</source>
        <translation></translation>
    </message>
    <message>
        <source>Black</source>
        <translation></translation>
    </message>
    <message>
        <source>Greek</source>
        <translation></translation>
    </message>
    <message>
        <source>Khmer</source>
        <translation></translation>
    </message>
    <message>
        <source>Latin</source>
        <translation></translation>
    </message>
    <message>
        <source>Light</source>
        <translation></translation>
    </message>
    <message>
        <source>Ogham</source>
        <translation></translation>
    </message>
    <message>
        <source>Oriya</source>
        <translation></translation>
    </message>
    <message>
        <source>Runic</source>
        <translation></translation>
    </message>
    <message>
        <source>Tamil</source>
        <translation></translation>
    </message>
    <message>
        <source>Cyrillic</source>
        <translation></translation>
    </message>
    <message>
        <source>Kannada</source>
        <translation></translation>
    </message>
    <message>
        <source>Malayalam</source>
        <translation></translation>
    </message>
    <message>
        <source>Simplified Chinese</source>
        <translation></translation>
    </message>
    <message>
        <source>Demi Bold</source>
        <translation></translation>
    </message>
    <message>
        <source>Arabic</source>
        <translation></translation>
    </message>
    <message>
        <source>Hebrew</source>
        <translation></translation>
    </message>
    <message>
        <source>Myanmar</source>
        <translation></translation>
    </message>
    <message>
        <source>Italic</source>
        <translation></translation>
    </message>
    <message>
        <source>Korean</source>
        <translation></translation>
    </message>
    <message>
        <source>Normal</source>
        <translation></translation>
    </message>
    <message>
        <source>Oblique</source>
        <translation></translation>
    </message>
    <message>
        <source>Telugu</source>
        <translation></translation>
    </message>
    <message>
        <source>Thaana</source>
        <translation></translation>
    </message>
    <message>
        <source>Symbol</source>
        <translation></translation>
    </message>
    <message>
        <source>Syriac</source>
        <translation></translation>
    </message>
    <message>
        <source>Devanagari</source>
        <translation></translation>
    </message>
    <message>
        <source>Japanese</source>
        <translation></translation>
    </message>
    <message>
        <source>Bengali</source>
        <translation></translation>
    </message>
    <message>
        <source>Armenian</source>
        <translation></translation>
    </message>
    <message>
        <source>Sinhala</source>
        <translation></translation>
    </message>
    <message>
        <source>Tibetan</source>
        <translation></translation>
    </message>
    <message>
        <source>Vietnamese</source>
        <translation></translation>
    </message>
    <message>
        <source>Gujarati</source>
        <translation></translation>
    </message>
    <message>
        <source>Traditional Chinese</source>
        <translation></translation>
    </message>
    <message>
        <source>Georgian</source>
        <translation></translation>
    </message>
    <message>
        <source>Gurmukhi</source>
        <translation></translation>
    </message>
</context>
</TS>
